version: '3.7.9'

services:
  django:
    command: gunicorn waycollect.wsgi:application --bind 0.0.0.0:8000
    build: .
    volumes:
     - data_base_g7mat:/home/app/banco
     - static_dir_g7mat:/home/app/main
    ports:
      - "8009:8000"
  nginx:
    build: ./nginx
    ports:
    - 90:90
    volumes:
      - static_dir:/home/app/main

volumes:
  data_base_g7mat: 
  static_dir_g7mat:
      