# Generated by Django 4.1.3 on 2022-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(upload_to='logo_empresa'),
        ),
    ]
